### ISSUE TITLE
Task Tracker: Update Documentation, CLI and Deployment files for better UX

### ISSUE THREAD

**Issue by embano1** [openfaas-incubator/openfaas-vcenter-connector#14]
In order to make it easier for users to try out the connector, we should work on the following

- [x] Restructure deployment and build files (govc, vcsim) into separate folders
- [ ] Deployment files for Docker Swarm/ compose (#4)
- [x] Update deployment manifests with (trusted) images built for the `openfaas` Docker org
- [x] Update README with new deployment locations/files
- [x] Add examples (#7)

**Comment by alexellis** [comment]
Please can we put the files in a similar format to the Kafka connector repo?

**Comment by embano1** [comment]
Updated PR #12
